# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window_real.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_channels = QtWidgets.QWidget()
        self.tab_channels.setObjectName("tab_channels")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_channels)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_channels)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1238, 607))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = A_widget(self.scrollAreaWidgetContents)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setObjectName("widget")
        self.verticalLayout_2.addWidget(self.widget)
        self.widget_2 = B_widget(self.scrollAreaWidgetContents)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2.addWidget(self.widget_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab_channels, "")
        self.tab_diagram = QtWidgets.QWidget()
        self.tab_diagram.setObjectName("tab_diagram")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_diagram)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tab_diagram)
        self.scrollArea_3.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 1226, 1016))
        self.scrollAreaWidgetContents_3.setMinimumSize(QtCore.QSize(1226, 1016))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.label_background = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_background.setGeometry(QtCore.QRect(9, 9, 1226, 1016))
        self.label_background.setMinimumSize(QtCore.QSize(1226, 1016))
        self.label_background.setText("")
        self.label_background.setObjectName("label_background")
        self.pushButton_V1C = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_V1C.setGeometry(QtCore.QRect(210, 273, 21, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_V1C.setFont(font)
        self.pushButton_V1C.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(239, 41, 41);")
        self.pushButton_V1C.setObjectName("pushButton_V1C")
        self.pushButton_V1C_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_V1C_2.setGeometry(QtCore.QRect(20, 280, 21, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_V1C_2.setFont(font)
        self.pushButton_V1C_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(239, 41, 41);")
        self.pushButton_V1C_2.setObjectName("pushButton_V1C_2")
        self.pushButton_V1C_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_V1C_3.setGeometry(QtCore.QRect(140, 390, 21, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_V1C_3.setFont(font)
        self.pushButton_V1C_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(239, 41, 41);")
        self.pushButton_V1C_3.setObjectName("pushButton_V1C_3")
        self.pushButton_V1C_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_V1C_4.setGeometry(QtCore.QRect(180, 140, 21, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_V1C_4.setFont(font)
        self.pushButton_V1C_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(239, 41, 41);")
        self.pushButton_V1C_4.setObjectName("pushButton_V1C_4")
        self.pushButton_V1C_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_V1C_5.setGeometry(QtCore.QRect(323, 75, 21, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_V1C_5.setFont(font)
        self.pushButton_V1C_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(239, 41, 41);")
        self.pushButton_V1C_5.setObjectName("pushButton_V1C_5")
        self.pushButton_V1C_6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_V1C_6.setGeometry(QtCore.QRect(760, 65, 21, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_V1C_6.setFont(font)
        self.pushButton_V1C_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(239, 41, 41);")
        self.pushButton_V1C_6.setObjectName("pushButton_V1C_6")
        self.pushButton_V1C_7 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_V1C_7.setGeometry(QtCore.QRect(880, 610, 31, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_V1C_7.setFont(font)
        self.pushButton_V1C_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(239, 41, 41);")
        self.pushButton_V1C_7.setObjectName("pushButton_V1C_7")
        self.pushButton_V1C_8 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_V1C_8.setGeometry(QtCore.QRect(20, 330, 21, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_V1C_8.setFont(font)
        self.pushButton_V1C_8.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.pushButton_V1C_8.setObjectName("pushButton_V1C_8")
        self.pushButton_V1C_9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_V1C_9.setGeometry(QtCore.QRect(140, 440, 21, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_V1C_9.setFont(font)
        self.pushButton_V1C_9.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.pushButton_V1C_9.setObjectName("pushButton_V1C_9")
        self.pushButton_V1C_10 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_V1C_10.setGeometry(QtCore.QRect(210, 323, 21, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_V1C_10.setFont(font)
        self.pushButton_V1C_10.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.pushButton_V1C_10.setObjectName("pushButton_V1C_10")
        self.pushButton_V1C_11 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_V1C_11.setGeometry(QtCore.QRect(180, 190, 21, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_V1C_11.setFont(font)
        self.pushButton_V1C_11.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.pushButton_V1C_11.setObjectName("pushButton_V1C_11")
        self.pushButton_V1C_12 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_V1C_12.setGeometry(QtCore.QRect(323, 125, 21, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_V1C_12.setFont(font)
        self.pushButton_V1C_12.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.pushButton_V1C_12.setObjectName("pushButton_V1C_12")
        self.pushButton_V1C_13 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_V1C_13.setGeometry(QtCore.QRect(760, 115, 21, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_V1C_13.setFont(font)
        self.pushButton_V1C_13.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.pushButton_V1C_13.setObjectName("pushButton_V1C_13")
        self.pushButton_V1C_14 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_V1C_14.setGeometry(QtCore.QRect(880, 660, 31, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_V1C_14.setFont(font)
        self.pushButton_V1C_14.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.pushButton_V1C_14.setObjectName("pushButton_V1C_14")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_3.setGeometry(QtCore.QRect(855, 100, 67, 17))
        self.label_3.setStyleSheet("background-color: rgb(239, 41, 41);\n"
"color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_4.setGeometry(QtCore.QRect(850, 580, 67, 17))
        self.label_4.setStyleSheet("background-color: rgb(239, 41, 41);\n"
"color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_5.setGeometry(QtCore.QRect(0, 310, 67, 17))
        self.label_5.setStyleSheet("background-color: rgb(239, 41, 41);\n"
"color: rgb(255, 255, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_6.setGeometry(QtCore.QRect(115, 420, 67, 17))
        self.label_6.setStyleSheet("background-color: rgb(239, 41, 41);\n"
"color: rgb(255, 255, 255);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_7.setGeometry(QtCore.QRect(110, 330, 67, 17))
        self.label_7.setStyleSheet("background-color: rgb(239, 41, 41);\n"
"color: rgb(255, 255, 255);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_8.setGeometry(QtCore.QRect(160, 170, 67, 17))
        self.label_8.setStyleSheet("background-color: rgb(239, 41, 41);\n"
"color: rgb(255, 255, 255);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_9.setGeometry(QtCore.QRect(350, 50, 67, 17))
        self.label_9.setStyleSheet("background-color: rgb(239, 41, 41);\n"
"color: rgb(255, 255, 255);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_6.addWidget(self.scrollArea_3)
        self.tabWidget.addTab(self.tab_diagram, "")
        self.tab_terminal = QtWidgets.QWidget()
        self.tab_terminal.setObjectName("tab_terminal")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_terminal)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_terminal)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1238, 607))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton.setCheckable(True)
        self.pushButton.setChecked(False)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label.setMaximumSize(QtCore.QSize(160, 16777215))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit.setText("")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 2, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout.addWidget(self.widget_3, 0, 4, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.textEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_5.addWidget(self.textEdit)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.scrollArea_2)
        self.tabWidget.addTab(self.tab_terminal, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Valve Controller"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_channels), _translate("MainWindow", "Channels"))
        self.pushButton_V1C.setText(_translate("MainWindow", "C2"))
        self.pushButton_V1C_2.setText(_translate("MainWindow", "C1"))
        self.pushButton_V1C_3.setText(_translate("MainWindow", "C3"))
        self.pushButton_V1C_4.setText(_translate("MainWindow", "C6"))
        self.pushButton_V1C_5.setText(_translate("MainWindow", "C4"))
        self.pushButton_V1C_6.setText(_translate("MainWindow", "C9"))
        self.pushButton_V1C_7.setText(_translate("MainWindow", "C13"))
        self.pushButton_V1C_8.setText(_translate("MainWindow", "O1"))
        self.pushButton_V1C_9.setText(_translate("MainWindow", "O3"))
        self.pushButton_V1C_10.setText(_translate("MainWindow", "O2"))
        self.pushButton_V1C_11.setText(_translate("MainWindow", "O6"))
        self.pushButton_V1C_12.setText(_translate("MainWindow", "O4"))
        self.pushButton_V1C_13.setText(_translate("MainWindow", "O9"))
        self.pushButton_V1C_14.setText(_translate("MainWindow", "O13"))
        self.label_3.setText(_translate("MainWindow", "CLOSED"))
        self.label_4.setText(_translate("MainWindow", "CLOSED"))
        self.label_5.setText(_translate("MainWindow", "CLOSED"))
        self.label_6.setText(_translate("MainWindow", "CLOSED"))
        self.label_7.setText(_translate("MainWindow", "CLOSED"))
        self.label_8.setText(_translate("MainWindow", "CLOSED"))
        self.label_9.setText(_translate("MainWindow", "CLOSED"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_diagram), _translate("MainWindow", "Diagram"))
        self.pushButton.setText(_translate("MainWindow", "USB Connect"))
        self.label_2.setText(_translate("MainWindow", "s"))
        self.label.setText(_translate("MainWindow", "Time since last packet:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_terminal), _translate("MainWindow", "Terminal"))

from .A_widget import A_widget
from .B_widget import B_widget
