# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window_real.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_channels = QtWidgets.QWidget()
        self.tab_channels.setObjectName("tab_channels")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_channels)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_channels)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1238, 607))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_A = A_widget(self.scrollAreaWidgetContents)
        self.widget_A.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_A.setObjectName("widget_A")
        self.verticalLayout_2.addWidget(self.widget_A)
        self.widget_B = B_widget(self.scrollAreaWidgetContents)
        self.widget_B.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_B.setObjectName("widget_B")
        self.verticalLayout_2.addWidget(self.widget_B)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab_channels, "")
        self.tab_diagram = QtWidgets.QWidget()
        self.tab_diagram.setObjectName("tab_diagram")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_diagram)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tab_diagram)
        self.scrollArea_3.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, -208, 1226, 1016))
        self.scrollAreaWidgetContents_3.setMinimumSize(QtCore.QSize(1226, 1016))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.label_background = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_background.setGeometry(QtCore.QRect(9, 9, 1226, 1016))
        self.label_background.setMinimumSize(QtCore.QSize(1226, 1016))
        self.label_background.setText("")
        self.label_background.setObjectName("label_background")
        self.pushButton_VC2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_VC2.setGeometry(QtCore.QRect(210, 273, 21, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_VC2.setFont(font)
        self.pushButton_VC2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(239, 41, 41);")
        self.pushButton_VC2.setObjectName("pushButton_VC2")
        self.pushButton_VC1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_VC1.setGeometry(QtCore.QRect(20, 280, 21, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_VC1.setFont(font)
        self.pushButton_VC1.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(239, 41, 41);")
        self.pushButton_VC1.setObjectName("pushButton_VC1")
        self.pushButton_VC3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_VC3.setGeometry(QtCore.QRect(140, 390, 21, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_VC3.setFont(font)
        self.pushButton_VC3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(239, 41, 41);")
        self.pushButton_VC3.setObjectName("pushButton_VC3")
        self.pushButton_VC6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_VC6.setGeometry(QtCore.QRect(180, 140, 21, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_VC6.setFont(font)
        self.pushButton_VC6.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(239, 41, 41);")
        self.pushButton_VC6.setObjectName("pushButton_VC6")
        self.pushButton_VC4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_VC4.setGeometry(QtCore.QRect(323, 75, 21, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_VC4.setFont(font)
        self.pushButton_VC4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(239, 41, 41);")
        self.pushButton_VC4.setObjectName("pushButton_VC4")
        self.pushButton_VC9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_VC9.setGeometry(QtCore.QRect(760, 65, 21, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_VC9.setFont(font)
        self.pushButton_VC9.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(239, 41, 41);")
        self.pushButton_VC9.setObjectName("pushButton_VC9")
        self.pushButton_VC13 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_VC13.setGeometry(QtCore.QRect(880, 610, 31, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_VC13.setFont(font)
        self.pushButton_VC13.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(239, 41, 41);")
        self.pushButton_VC13.setObjectName("pushButton_VC13")
        self.pushButton_VO1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_VO1.setGeometry(QtCore.QRect(20, 330, 21, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_VO1.setFont(font)
        self.pushButton_VO1.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.pushButton_VO1.setObjectName("pushButton_VO1")
        self.pushButton_VO3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_VO3.setGeometry(QtCore.QRect(140, 440, 21, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_VO3.setFont(font)
        self.pushButton_VO3.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.pushButton_VO3.setObjectName("pushButton_VO3")
        self.pushButton_VO2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_VO2.setGeometry(QtCore.QRect(210, 323, 21, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_VO2.setFont(font)
        self.pushButton_VO2.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.pushButton_VO2.setObjectName("pushButton_VO2")
        self.pushButton_VO6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_VO6.setGeometry(QtCore.QRect(180, 190, 21, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_VO6.setFont(font)
        self.pushButton_VO6.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.pushButton_VO6.setObjectName("pushButton_VO6")
        self.pushButton_VO4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_VO4.setGeometry(QtCore.QRect(323, 125, 21, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_VO4.setFont(font)
        self.pushButton_VO4.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.pushButton_VO4.setObjectName("pushButton_VO4")
        self.pushButton_VO9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_VO9.setGeometry(QtCore.QRect(760, 115, 21, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_VO9.setFont(font)
        self.pushButton_VO9.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.pushButton_VO9.setObjectName("pushButton_VO9")
        self.pushButton_VO13 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_VO13.setGeometry(QtCore.QRect(880, 660, 31, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_VO13.setFont(font)
        self.pushButton_VO13.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.pushButton_VO13.setObjectName("pushButton_VO13")
        self.label_V9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_V9.setGeometry(QtCore.QRect(855, 100, 67, 17))
        self.label_V9.setStyleSheet("background-color: rgb(239, 41, 41);\n"
"color: rgb(255, 255, 255);")
        self.label_V9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_V9.setObjectName("label_V9")
        self.label_V13 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_V13.setGeometry(QtCore.QRect(850, 580, 67, 17))
        self.label_V13.setStyleSheet("background-color: rgb(239, 41, 41);\n"
"color: rgb(255, 255, 255);")
        self.label_V13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_V13.setObjectName("label_V13")
        self.label_V1 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_V1.setGeometry(QtCore.QRect(0, 310, 67, 17))
        self.label_V1.setStyleSheet("background-color: rgb(239, 41, 41);\n"
"color: rgb(255, 255, 255);")
        self.label_V1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_V1.setObjectName("label_V1")
        self.label_V3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_V3.setGeometry(QtCore.QRect(115, 420, 67, 17))
        self.label_V3.setStyleSheet("background-color: rgb(239, 41, 41);\n"
"color: rgb(255, 255, 255);")
        self.label_V3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_V3.setObjectName("label_V3")
        self.label_V2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_V2.setGeometry(QtCore.QRect(110, 330, 67, 17))
        self.label_V2.setStyleSheet("background-color: rgb(239, 41, 41);\n"
"color: rgb(255, 255, 255);")
        self.label_V2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_V2.setObjectName("label_V2")
        self.label_V6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_V6.setGeometry(QtCore.QRect(160, 170, 67, 17))
        self.label_V6.setStyleSheet("background-color: rgb(239, 41, 41);\n"
"color: rgb(255, 255, 255);")
        self.label_V6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_V6.setObjectName("label_V6")
        self.label_V4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_V4.setGeometry(QtCore.QRect(350, 50, 67, 17))
        self.label_V4.setStyleSheet("background-color: rgb(239, 41, 41);\n"
"color: rgb(255, 255, 255);")
        self.label_V4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_V4.setObjectName("label_V4")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_6.addWidget(self.scrollArea_3)
        self.tabWidget.addTab(self.tab_diagram, "")
        self.tab_terminal = QtWidgets.QWidget()
        self.tab_terminal.setObjectName("tab_terminal")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_terminal)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_terminal)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1238, 607))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonUsbConnect = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButtonUsbConnect.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButtonUsbConnect.setCheckable(True)
        self.pushButtonUsbConnect.setChecked(True)
        self.pushButtonUsbConnect.setObjectName("pushButtonUsbConnect")
        self.gridLayout.addWidget(self.pushButtonUsbConnect, 0, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label.setMaximumSize(QtCore.QSize(160, 16777215))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit.setText("")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 2, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout.addWidget(self.widget_3, 0, 4, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.textEdit_printout = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.textEdit_printout.setReadOnly(True)
        self.textEdit_printout.setObjectName("textEdit_printout")
        self.verticalLayout_5.addWidget(self.textEdit_printout)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.scrollArea_2)
        self.tabWidget.addTab(self.tab_terminal, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Valve Controller"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_channels), _translate("MainWindow", "Channels"))
        self.pushButton_VC2.setText(_translate("MainWindow", "C2"))
        self.pushButton_VC1.setText(_translate("MainWindow", "C1"))
        self.pushButton_VC3.setText(_translate("MainWindow", "C3"))
        self.pushButton_VC6.setText(_translate("MainWindow", "C6"))
        self.pushButton_VC4.setText(_translate("MainWindow", "C4"))
        self.pushButton_VC9.setText(_translate("MainWindow", "C9"))
        self.pushButton_VC13.setText(_translate("MainWindow", "C13"))
        self.pushButton_VO1.setText(_translate("MainWindow", "O1"))
        self.pushButton_VO3.setText(_translate("MainWindow", "O3"))
        self.pushButton_VO2.setText(_translate("MainWindow", "O2"))
        self.pushButton_VO6.setText(_translate("MainWindow", "O6"))
        self.pushButton_VO4.setText(_translate("MainWindow", "O4"))
        self.pushButton_VO9.setText(_translate("MainWindow", "O9"))
        self.pushButton_VO13.setText(_translate("MainWindow", "O13"))
        self.label_V9.setText(_translate("MainWindow", "CLOSED"))
        self.label_V13.setText(_translate("MainWindow", "CLOSED"))
        self.label_V1.setText(_translate("MainWindow", "CLOSED"))
        self.label_V3.setText(_translate("MainWindow", "CLOSED"))
        self.label_V2.setText(_translate("MainWindow", "CLOSED"))
        self.label_V6.setText(_translate("MainWindow", "CLOSED"))
        self.label_V4.setText(_translate("MainWindow", "CLOSED"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_diagram), _translate("MainWindow", "Diagram"))
        self.pushButtonUsbConnect.setText(_translate("MainWindow", "USB Disconnect"))
        self.label_2.setText(_translate("MainWindow", "s"))
        self.label.setText(_translate("MainWindow", "Time since last packet:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_terminal), _translate("MainWindow", "Terminal"))

from .A_widget import A_widget
from .B_widget import B_widget
